# -*- coding: utf-8 -*-
"""PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zh07qCXDnZMpIBiG7peXIp4Oth1Y-BA4
"""

import numpy as np
import pickle
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

data = pd.read_csv('/content/Customer Data (1).csv')

data.head()

data.info()

data.isnull().sum()

data.describe()

data.drop('CUST_ID', axis=1)

# 3. Handle Missing Values

# Drop 'CUST_ID' as it's not a numeric feature and not relevant for imputation
data_for_imputation = data.drop('CUST_ID', axis=1)

imputer = SimpleImputer(strategy='mean')
# Impute missing values and update the 'data' DataFrame
data_imputed_array = imputer.fit_transform(data_for_imputation)
data = pd.DataFrame(data_imputed_array, columns=data_for_imputation.columns)

# 4. Feature Scaling
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

sns.scatterplot(data=data, x='BALANCE', y='PURCHASES')
plt.title('Balance vs Purchases')
plt.show()

numeric_features = data[['BALANCE', 'PURCHASES']]

scaler = StandardScaler()
scaled_features = scaler.fit_transform(numeric_features)

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(scaled_features)
    wcss.append(kmeans.inertia_)

# Plot the Elbow Method graph
plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.xlabel('Number of Clusters (K)')
plt.ylabel('WCSS')
plt.title('Elbow Method to Find Optimal K')
plt.show()

kmeans = KMeans(n_clusters=3, random_state=42)
clusters = kmeans.fit_predict(scaled_data)

data['Cluster'] = clusters
plt.figure(figsize=(10, 6))
plt.scatter(data['BALANCE'], data['PURCHASES'], c=data['Cluster'], cmap='viridis')
plt.xlabel('BALANCE')
plt.ylabel('PURCHASES')
plt.title('K-means Clustering')
plt.show()

sns.pairplot(data[['BALANCE', 'PURCHASES']])
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(10,6))
sns.scatterplot(data=pca_df, x='PC1', y='PC2', hue='Cluster', palette='viridis')
plt.title('Customer Segments (PCA Visualization)')
plt.show()

from sklearn.decomposition import PCA

# Apply PCA on the full scaled data, as this was used for clustering
pca = PCA(n_components=2)
principal_components = pca.fit_transform(scaled_data)
pca_df = pd.DataFrame(data=principal_components, columns=['PC1', 'PC2'])

# Add the Cluster column from the original data DataFrame
pca_df['Cluster'] = data['Cluster']

pickle.dump(kmeans, open('cluster_model.pkl', 'wb'))
pickle.dump(scaler, open('scaler.pkl', 'wb'))

